# Generated by Django 6.0.1 on 2026-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
